[build]
  functions = ".netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/auth-manipulation"
  to = "/.netlify/functions/auth-manipulation"
  status = 200

[[redirects]]
  from = "/api/login"  # New route for login function
  to = "/.netlify/functions/login"  # Redirect to the login function
  status = 200

[[redirects]]
  from = "/api/file-handler"
  to = "/.netlify/functions/file-handler"
  status = 200